name: CI
permissions:
  contents: read

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - master
    # To avoid errors on tag pushes, ensure it only triggers for commits
    tags:
      - "*"

jobs:
  setup_release:
    name: Setup Release
    outputs:
      publish_release: ${{ steps.setup_release.outputs.publish_release }}
      release_body: ${{ steps.setup_release.outputs.release_body }}
      release_commit: ${{ steps.setup_release.outputs.release_commit }}
      release_generate_release_notes: ${{ steps.setup_release.outputs.release_generate_release_notes }}
      release_tag: ${{ steps.setup_release.outputs.release_tag }}
      release_version: ${{ steps.setup_release.outputs.release_version }}
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Release
        id: setup_release
        uses: LizardByte/setup-release-action@v2025.426.225
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine commit and branch details
        run: |
          if [[ "${{ github.event_name }}" == "push" ]]; then
            if [[ "${{ github.ref }}" == refs/heads/* ]]; then
              echo "This is a commit push event"
              echo "commit=${{ github.sha }}" >> $GITHUB_ENV
              echo "branch=${{ github.ref_name }}" >> $GITHUB_ENV
            else
              echo "This is a tag push event, skipping commit related steps."
            fi
          elif [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "This is a PR event"
            echo "commit=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV
            echo "branch=${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV
          fi

      - name: Debug commit and branch info
        run: |
          echo "Commit: ${{ env.commit }}"
          echo "Branch: ${{ env.branch }}"
